-- 1. Tabela de Usuários (Simplificada para Google Login)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255), -- Pode ser NULL para login social
    avatar VARCHAR(1024),
    annual_reading_goal INT DEFAULT 12,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabela de Livros (Catálogo Global)
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publisher VARCHAR(255),
    publication_year INT,
    isbn VARCHAR(20) UNIQUE,
    pages INT,
    cover_image_url VARCHAR(2048),
    google_books_id VARCHAR(255) UNIQUE,
    synopsis TEXT,
    price DECIMAL(10, 2),
    purchase_url VARCHAR(2048)
);

CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_author ON books(author);

-- 3. Tabela de Vínculo (Minha Biblioteca)
CREATE TABLE user_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL, -- WANT_TO_READ, TO_READ, READING, READ
    rating INT,
    review TEXT,
    current_page INT DEFAULT 0,
    added_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_reading_at TIMESTAMP WITH TIME ZONE,
    finished_reading_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_user_books_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_books_book FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_book UNIQUE (user_id, book_id)
);

-- 4. Tabela de Empréstimos
CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_book_id BIGINT NOT NULL,
    borrower_name VARCHAR(255) NOT NULL,
    borrower_email VARCHAR(255),
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    notes TEXT,

    CONSTRAINT fk_loans_user_book FOREIGN KEY (user_book_id) REFERENCES user_books(id) ON DELETE CASCADE
);

-- 5. Tabela de Histórico de Atividades
CREATE TABLE user_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action_type VARCHAR(50),
    description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);