-- V2: Cria a tabela global de livros (Catálogo)
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publisher VARCHAR(255),
    publication_year INT,
    isbn VARCHAR(20) UNIQUE, -- ISBN deve ser único
    pages INT,
    cover_image_url VARCHAR(2048),
    google_books_id VARCHAR(255) UNIQUE -- ID do Google Books para fácil integração
);

-- Adiciona índices para buscas rápidas
CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_author ON books(author);
CREATE INDEX idx_books_isbn ON books(isbn);