-- V4: Cria a tabela de junção "Biblioteca Pessoal" (UserBooks)
CREATE TABLE user_books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,

    -- CORREÇÃO: Trocamos o tipo "reading_status" por VARCHAR
    status VARCHAR(50) NOT NULL,

    rating INT, -- Nota do usuário (ex: 1 a 5)
    review TEXT, -- Resenha

    added_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_reading_at TIMESTAMP WITH TIME ZONE,
    finished_reading_at TIMESTAMP WITH TIME ZONE,

    -- Chaves Estrangeiras
    CONSTRAINT fk_user_books_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_books_book
        FOREIGN KEY(book_id)
        REFERENCES books(id)
        ON DELETE CASCADE,

    -- Garante que um usuário só pode ter um livro uma vez na estante
    CONSTRAINT uk_user_book UNIQUE (user_id, book_id)
);

-- Índices para performance
CREATE INDEX idx_user_books_user_id ON user_books(user_id);
CREATE INDEX idx_user_books_book_id ON user_books(book_id);